// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _754: x0 => x0.baseURI,
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _923: x0 => x0.text(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1193: x0 => x0.initialData,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1281: x0 => x0.requestFullscreen(),
      _1282: x0 => x0.exitFullscreen(),
      _1283: (x0,x1) => x0.append(x1),
      _1284: (x0,x1,x2) => x0.call(x1,x2),
      _1285: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1285(f,arguments.length,x0,x1) }),
      _1286: x0 => new ResizeObserver(x0),
      _1287: (x0,x1) => x0.observe(x1),
      _1288: (x0,x1,x2,x3) => x0.call(x1,x2,x3),
      _1289: x0 => x0.arrayBuffer(),
      _1291: (x0,x1,x2) => x0.toBlob(x1,x2),
      _1292: (x0,x1) => x0.call(x1),
      _1293: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20) => x0.call(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20),
      _1294: x0 => x0.call(),
      _1295: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1295(f,arguments.length,x0) }),
      _1296: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1296(f,arguments.length,x0) }),
      _1297: x0 => x0.call(),
      _1298: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1298(f,arguments.length,x0,x1,x2,x3) }),
      _1299: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1299(f,arguments.length,x0) }),
      _1300: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1300(f,arguments.length,x0,x1,x2) }),
      _1301: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1301(f,arguments.length,x0,x1,x2,x3) }),
      _1302: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4,x5,x6,x7,x8) { return module.exports._1302(f,arguments.length,x0,x1,x2,x3,x4,x5,x6,x7,x8) }),
      _1303: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1303(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1304: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1304(f,arguments.length,x0,x1) }),
      _1305: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1305(f,arguments.length,x0) }),
      _1306: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1306(f,arguments.length,x0) }),
      _1307: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4,x5,x6) { return module.exports._1307(f,arguments.length,x0,x1,x2,x3,x4,x5,x6) }),
      _1308: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1308(f,arguments.length,x0,x1,x2) }),
      _1309: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1309(f,arguments.length,x0,x1,x2) }),
      _1310: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1310(f,arguments.length,x0,x1,x2) }),
      _1311: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1311(f,arguments.length,x0) }),
      _1312: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1312(f,arguments.length,x0) }),
      _1313: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1313(f,arguments.length,x0) }),
      _1314: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1314(f,arguments.length,x0) }),
      _1315: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1315(f,arguments.length,x0) }),
      _1316: (x0,x1,x2,x3,x4) => x0.call(x1,x2,x3,x4),
      _1317: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1317(f,arguments.length,x0,x1) }),
      _1318: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1318(f,arguments.length,x0,x1) }),
      _1319: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1319(f,arguments.length,x0,x1) }),
      _1320: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1320(f,arguments.length,x0,x1) }),
      _1321: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1321(f,arguments.length,x0,x1) }),
      _1322: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1322(f,arguments.length,x0,x1) }),
      _1323: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1323(f,arguments.length,x0,x1) }),
      _1324: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1324(f,arguments.length,x0,x1) }),
      _1325: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1325(f,arguments.length,x0,x1) }),
      _1326: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1326(f,arguments.length,x0) }),
      _1327: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11) => x0.call(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11),
      _1328: (x0,x1,x2,x3,x4) => x0.call(x1,x2,x3,x4),
      _1330: (x0,x1,x2,x3,x4,x5) => x0.call(x1,x2,x3,x4,x5),
      _1331: (x0,x1,x2,x3,x4,x5,x6,x7,x8) => x0.call(x1,x2,x3,x4,x5,x6,x7,x8),
      _1340: (x0,x1,x2,x3,x4,x5,x6) => x0.call(x1,x2,x3,x4,x5,x6),
      _1357: x0 => x0.createRange(),
      _1358: (x0,x1) => x0.selectNode(x1),
      _1359: x0 => x0.getSelection(),
      _1360: x0 => x0.removeAllRanges(),
      _1361: (x0,x1) => x0.addRange(x1),
      _1362: (x0,x1) => x0.createElement(x1),
      _1363: (x0,x1) => x0.append(x1),
      _1364: (x0,x1,x2) => x0.insertRule(x1,x2),
      _1365: (x0,x1) => x0.add(x1),
      _1366: x0 => x0.preventDefault(),
      _1367: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1367(f,arguments.length,x0) }),
      _1368: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1369: (x0,x1) => x0.getUserMedia(x1),
      _1370: x0 => x0.getSupportedConstraints(),
      _1371: x0 => x0.getVideoTracks(),
      _1372: x0 => x0.getCapabilities(),
      _1373: x0 => x0.getSettings(),
      _1374: (x0,x1,x2) => x0.setProperty(x1,x2),
      _1375: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1376: x0 => x0.play(),
      _1377: x0 => x0.pause(),
      _1378: x0 => x0.getTracks(),
      _1379: x0 => x0.stop(),
      _1380: (x0,x1,x2) => x0.translate(x1,x2),
      _1381: (x0,x1,x2) => x0.scale(x1,x2),
      _1382: (x0,x1,x2,x3,x4,x5) => x0.drawImage(x1,x2,x3,x4,x5),
      _1383: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1383(f,arguments.length,x0) }),
      _1384: x0 => globalThis.URL.createObjectURL(x0),
      _1385: x0 => ({torch: x0}),
      _1386: (x0,x1) => x0.applyConstraints(x1),
      _1387: x0 => ({zoom: x0}),
      _1388: x0 => ({mimeType: x0}),
      _1389: (x0,x1) => new MediaRecorder(x0,x1),
      _1390: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1390(f,arguments.length,x0) }),
      _1391: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1392: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1392(f,arguments.length,x0) }),
      _1393: x0 => x0.start(),
      _1394: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1394(f,arguments.length,x0) }),
      _1395: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1396: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1396(f,arguments.length,x0) }),
      _1397: x0 => x0.pause(),
      _1398: x0 => x0.resume(),
      _1399: x0 => x0.stop(),
      _1400: x0 => x0.load(),
      _1401: x0 => globalThis.MediaRecorder.isTypeSupported(x0),
      _1402: x0 => ({type: x0}),
      _1403: (x0,x1) => new Blob(x0,x1),
      _1404: x0 => x0.enumerateDevices(),
      _1405: x0 => new Event(x0),
      _1406: x0 => x0.requestFullscreen(),
      _1407: (x0,x1) => x0.lock(x1),
      _1408: x0 => x0.unlock(),
      _1409: () => globalThis.window.navigator.userAgent,
      _1410: (x0,x1) => x0.get(x1),
      _1411: x0 => x0.text(),
      _1415: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1416: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1417: (x0,x1) => x0.createElement(x1),
      _1423: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1424: (x0,x1) => x0.canShare(x1),
      _1425: (x0,x1) => x0.share(x1),
      _1426: x0 => ({url: x0}),
      _1427: (x0,x1,x2) => ({files: x0,title: x1,text: x2}),
      _1428: (x0,x1) => ({files: x0,text: x1}),
      _1429: (x0,x1) => ({files: x0,title: x1}),
      _1430: x0 => ({files: x0}),
      _1431: (x0,x1) => ({title: x0,text: x1}),
      _1432: x0 => ({text: x0}),
      _1433: x0 => x0.click(),
      _1434: x0 => x0.remove(),
      _1435: () => ({}),
      _1436: (x0,x1,x2) => new File(x0,x1,x2),
      _1437: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1437(f,arguments.length,x0) }),
      _1438: (x0,x1,x2) => globalThis.jsConnect(x0,x1,x2),
      _1439: (x0,x1) => globalThis.jsSend(x0,x1),
      _1440: x0 => globalThis.jsDisconnect(x0),
      _1441: x0 => x0.read(),
      _1442: (x0,x1) => x0.getType(x1),
      _1443: x0 => new ClipboardItem(x0),
      _1444: (x0,x1) => x0.write(x1),
      _1445: x0 => x0.readText(),
      _1447: () => new FileReader(),
      _1453: x0 => ({audio: x0}),
      _1454: x0 => x0.getAudioTracks(),
      _1455: (x0,x1) => x0.removeTrack(x1),
      _1456: x0 => x0.close(),
      _1457: (x0,x1) => x0.warn(x1),
      _1458: x0 => ({sampleRate: x0}),
      _1459: x0 => new AudioContext(x0),
      _1460: () => new AudioContext(),
      _1461: x0 => x0.suspend(),
      _1462: x0 => x0.resume(),
      _1463: (x0,x1) => x0.connect(x1),
      _1464: (x0,x1) => x0.createMediaStreamSource(x1),
      _1465: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1465(f,arguments.length,x0) }),
      _1466: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1466(f,arguments.length,x0) }),
      _1467: (x0,x1) => x0.addModule(x1),
      _1468: x0 => ({parameterData: x0}),
      _1469: (x0,x1,x2) => new AudioWorkletNode(x0,x1,x2),
      _1470: x0 => ({name: x0}),
      _1471: (x0,x1) => x0.query(x1),
      _1472: x0 => globalThis.URL.revokeObjectURL(x0),
      _1475: x0 => x0.disconnect(),
      _1476: (x0,x1,x2) => ({mimeType: x0,audioBitsPerSecond: x1,bitsPerSecond: x2}),
      _1477: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1477(f,arguments.length,x0) }),
      _1478: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1478(f,arguments.length,x0) }),
      _1479: (x0,x1) => x0.start(x1),
      _1480: (x0,x1) => globalThis.jsFixWebmDuration(x0,x1),
      _1481: x0 => x0.createAnalyser(),
      _1482: (x0,x1) => x0.getFloatFrequencyData(x1),
      _1483: x0 => x0.decode(),
      _1484: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1485: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1486: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1486(f,arguments.length,x0) }),
      _1487: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1487(f,arguments.length,x0) }),
      _1488: x0 => x0.send(),
      _1489: () => new XMLHttpRequest(),
      _1490: x0 => globalThis.Wakelock.toggle(x0),
      _1491: () => globalThis.Wakelock.enabled(),
      _1492: (x0,x1) => ({video: x0,audio: x1}),
      _1493: (x0,x1) => x0.createMediaElementSource(x1),
      _1494: x0 => x0.createStereoPanner(),
      _1495: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1495(f,arguments.length,x0) }),
      _1496: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1496(f,arguments.length,x0) }),
      _1497: (x0,x1,x2) => ({enableHighAccuracy: x0,timeout: x1,maximumAge: x2}),
      _1498: (x0,x1,x2,x3) => x0.getCurrentPosition(x1,x2,x3),
      _1499: (x0,x1) => x0.clearWatch(x1),
      _1500: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1500(f,arguments.length,x0) }),
      _1501: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1501(f,arguments.length,x0) }),
      _1502: (x0,x1,x2,x3) => x0.watchPosition(x1,x2,x3),
      _1503: (x0,x1) => x0.getItem(x1),
      _1504: (x0,x1) => x0.removeItem(x1),
      _1505: (x0,x1,x2) => x0.setItem(x1,x2),
      _1506: x0 => ({frequency: x0}),
      _1507: x0 => new Accelerometer(x0),
      _1508: x0 => x0.start(),
      _1509: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1509(f,arguments.length,x0) }),
      _1510: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1510(f,arguments.length,x0) }),
      _1511: x0 => new Gyroscope(x0),
      _1512: x0 => x0.start(),
      _1513: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1513(f,arguments.length,x0) }),
      _1514: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1514(f,arguments.length,x0) }),
      _1515: x0 => new LinearAccelerationSensor(x0),
      _1516: x0 => x0.start(),
      _1517: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1517(f,arguments.length,x0) }),
      _1518: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1518(f,arguments.length,x0) }),
      _1519: x0 => new Magnetometer(x0),
      _1520: x0 => x0.start(),
      _1521: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1521(f,arguments.length,x0) }),
      _1522: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1522(f,arguments.length,x0) }),
      _1523: x0 => ({name: x0}),
      _1524: x0 => ({video: x0}),
      _1525: () => globalThis.Notification.requestPermission(),
      _1526: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1526(f,arguments.length,x0) }),
      _1527: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1527(f,arguments.length,x0) }),
      _1528: (x0,x1,x2) => x0.getCurrentPosition(x1,x2),
      _1531: (x0,x1) => x0.querySelector(x1),
      _1532: (x0,x1) => x0.item(x1),
      _1533: (x0,x1) => x0.readAsDataURL(x1),
      _1534: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1535: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1535(f,arguments.length,x0) }),
      _1536: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1536(f,arguments.length,x0) }),
      _1537: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1537(f,arguments.length,x0) }),
      _1538: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1538(f,arguments.length,x0) }),
      _1539: (x0,x1) => x0.removeChild(x1),
      _1540: x0 => new Blob(x0),
      _1541: (x0,x1,x2) => x0.slice(x1,x2),
      _1542: x0 => x0.deviceMemory,
      _1543: x0 => x0.getBattery(),
      _1544: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1544(f,arguments.length,x0) }),
      _1545: (x0,x1) => x0.key(x1),
      _1546: (x0,x1,x2,x3,x4,x5,x6,x7) => x0.unwrapKey(x1,x2,x3,x4,x5,x6,x7),
      _1547: (x0,x1,x2,x3,x4,x5) => x0.importKey(x1,x2,x3,x4,x5),
      _1548: (x0,x1,x2,x3) => x0.generateKey(x1,x2,x3),
      _1549: (x0,x1,x2,x3,x4) => x0.wrapKey(x1,x2,x3,x4),
      _1550: (x0,x1,x2) => x0.exportKey(x1,x2),
      _1551: (x0,x1) => x0.getRandomValues(x1),
      _1552: (x0,x1,x2,x3) => x0.encrypt(x1,x2,x3),
      _1553: (x0,x1,x2,x3) => x0.decrypt(x1,x2,x3),
      _1555: (x0,x1) => x0.matchMedia(x1),
      _1558: x0 => x0.pyodide,
      _1559: x0 => x0.multiView,
      _1561: x0 => x0.webSocketEndpoint,
      _1562: x0 => x0.routeUrlStrategy,
      _1567: () => globalThis.flet,
      _1568: Date.now,
      _1570: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1571: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1572: () => new Error().stack,
      _1573: () => typeof dartUseDateNowForTicks !== "undefined",
      _1574: () => 1000 * performance.now(),
      _1575: () => Date.now(),
      _1576: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1577: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1578: () => new WeakMap(),
      _1579: (map, o) => map.get(o),
      _1580: (map, o, v) => map.set(o, v),
      _1581: (exn) => exn.toString(),
      _1582: (exn) => exn.stack,
      _1583: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1584: x0 => new WeakRef(x0),
      _1585: x0 => x0.deref(),
      _1586: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1586(f,arguments.length,x0) }),
      _1587: x0 => new FinalizationRegistry(x0),
      _1588: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _1589: (x0,x1,x2) => x0.register(x1,x2),
      _1590: (x0,x1) => x0.unregister(x1),
      _1592: () => globalThis.WeakRef,
      _1593: () => globalThis.FinalizationRegistry,
      _1595: s => JSON.stringify(s),
      _1596: s => printToConsole(s),
      _1597: (o, p, r) => o.replaceAll(p, () => r),
      _1598: (o, p, r) => o.replace(p, () => r),
      _1599: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1600: s => s.toUpperCase(),
      _1601: s => s.trim(),
      _1602: s => s.trimLeft(),
      _1603: s => s.trimRight(),
      _1604: (string, times) => string.repeat(times),
      _1605: Function.prototype.call.bind(String.prototype.indexOf),
      _1606: (s, p, i) => s.lastIndexOf(p, i),
      _1607: (string, token) => string.split(token),
      _1608: Object.is,
      _1611: (o, t) => typeof o === t,
      _1612: (o, c) => o instanceof c,
      _1613: o => Object.keys(o),
      _1615: (o,s,v) => o[s] = v,
      _1616: (o, a) => o + a,
      _1643: x0 => new Array(x0),
      _1645: x0 => x0.length,
      _1647: (x0,x1) => x0[x1],
      _1648: (x0,x1,x2) => { x0[x1] = x2 },
      _1649: (x0,x1) => x0.push(x1),
      _1651: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1653: x0 => new Int8Array(x0),
      _1654: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1656: x0 => new Uint8ClampedArray(x0),
      _1658: x0 => new Int16Array(x0),
      _1660: x0 => new Uint16Array(x0),
      _1662: x0 => new Int32Array(x0),
      _1664: x0 => new Uint32Array(x0),
      _1666: x0 => new Float32Array(x0),
      _1668: x0 => new Float64Array(x0),
      _1689: () => Symbol("jsBoxedDartObjectProperty"),
      _1690: x0 => x0.random(),
      _1691: (x0,x1) => x0.getRandomValues(x1),
      _1692: () => globalThis.crypto,
      _1693: () => globalThis.Math,
      _1706: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1707: (handle) => clearTimeout(handle),
      _1708: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1709: (handle) => clearInterval(handle),
      _1710: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1711: () => Date.now(),
      _1712: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1713: (x0,x1) => x0.exec(x1),
      _1714: (x0,x1) => x0.test(x1),
      _1715: x0 => x0.pop(),
      _1717: o => o === undefined,
      _1719: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1721: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1722: o => o instanceof RegExp,
      _1723: (l, r) => l === r,
      _1724: o => o,
      _1725: o => o,
      _1726: o => o,
      _1727: b => !!b,
      _1728: o => o.length,
      _1730: (o, i) => o[i],
      _1731: f => f.dartFunction,
      _1732: () => ({}),
      _1733: () => [],
      _1735: () => globalThis,
      _1736: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1737: (o, p) => p in o,
      _1738: (o, p) => o[p],
      _1739: (o, p, v) => o[p] = v,
      _1740: (o, m, a) => o[m].apply(o, a),
      _1742: o => String(o),
      _1743: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1744: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1744(f,arguments.length,x0) }),
      _1745: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1745(f,arguments.length,x0,x1) }),
      _1746: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1747: o => [o],
      _1748: (o0, o1) => [o0, o1],
      _1749: (o0, o1, o2) => [o0, o1, o2],
      _1750: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1751: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1752: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1753: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1754: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1755: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1756: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1757: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1758: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1759: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1760: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1761: x0 => new ArrayBuffer(x0),
      _1762: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1763: x0 => x0.input,
      _1764: x0 => x0.index,
      _1765: x0 => x0.groups,
      _1766: x0 => x0.flags,
      _1767: x0 => x0.multiline,
      _1768: x0 => x0.ignoreCase,
      _1769: x0 => x0.unicode,
      _1770: x0 => x0.dotAll,
      _1771: (x0,x1) => { x0.lastIndex = x1 },
      _1772: (o, p) => p in o,
      _1773: (o, p) => o[p],
      _1774: (o, p, v) => o[p] = v,
      _1775: (o, p) => delete o[p],
      _1776: (x0,x1) => x0.end(x1),
      _1777: (x0,x1) => x0.item(x1),
      _1778: (x0,x1) => x0.appendChild(x1),
      _1781: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1782: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1782(f,arguments.length,x0,x1) }),
      _1783: x0 => ({xhrSetup: x0}),
      _1784: x0 => new Hls(x0),
      _1785: (x0,x1) => x0.loadSource(x1),
      _1786: (x0,x1) => x0.attachMedia(x1),
      _1787: (x0,x1) => x0.canPlayType(x1),
      _1788: () => globalThis.Hls.isSupported(),
      _1789: () => new XMLHttpRequest(),
      _1790: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1793: x0 => x0.send(),
      _1795: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1795(f,arguments.length,x0) }),
      _1796: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1796(f,arguments.length,x0) }),
      _1801: (x0,x1) => new WebSocket(x0,x1),
      _1802: (x0,x1) => x0.send(x1),
      _1803: (x0,x1,x2) => x0.close(x1,x2),
      _1805: x0 => x0.close(),
      _1807: (x0,x1) => x0.append(x1),
      _1809: () => new AbortController(),
      _1810: x0 => x0.abort(),
      _1811: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _1812: (x0,x1) => globalThis.fetch(x0,x1),
      _1813: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1813(f,arguments.length,x0,x1,x2) }),
      _1814: (x0,x1) => x0.forEach(x1),
      _1815: x0 => x0.getReader(),
      _1816: x0 => x0.cancel(),
      _1817: x0 => x0.read(),
      _1819: x0 => x0.zoom,
      _1820: x0 => x0.torch,
      _1821: x0 => x0.zoom,
      _1822: x0 => x0.torch,
      _1823: x0 => x0.facingMode,
      _1824: x0 => x0.facingMode,
      _1826: x0 => x0.max,
      _1828: x0 => x0.min,
      _1833: (x0,x1,x2,x3) => ({method: x0,headers: x1,body: x2,credentials: x3}),
      _1834: (x0,x1,x2) => x0.fetch(x1,x2),
      _1835: o => o instanceof Array,
      _1836: (a, i) => a.push(i),
      _1837: (a, i) => a.splice(i, 1)[0],
      _1838: (a, i, v) => a.splice(i, 0, v),
      _1839: (a, l) => a.length = l,
      _1840: a => a.pop(),
      _1841: (a, i) => a.splice(i, 1),
      _1843: (a, s, e) => a.slice(s, e),
      _1845: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _1846: a => a.length,
      _1847: (a, l) => a.length = l,
      _1848: (a, i) => a[i],
      _1849: (a, i, v) => a[i] = v,
      _1851: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1852: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1853: o => o instanceof DataView,
      _1854: o => o instanceof Uint8Array,
      _1855: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1856: o => o instanceof Int8Array,
      _1857: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1858: o => o instanceof Uint8ClampedArray,
      _1859: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1860: o => o instanceof Uint16Array,
      _1861: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1862: o => o instanceof Int16Array,
      _1863: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1864: o => o instanceof Uint32Array,
      _1865: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1866: o => o instanceof Int32Array,
      _1867: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1869: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1870: o => o instanceof Float32Array,
      _1871: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1872: o => o instanceof Float64Array,
      _1873: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1874: (t, s) => t.set(s),
      _1875: l => new DataView(new ArrayBuffer(l)),
      _1876: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1877: o => o.byteLength,
      _1878: o => o.buffer,
      _1879: o => o.byteOffset,
      _1880: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1881: (b, o) => new DataView(b, o),
      _1882: (b, o, l) => new DataView(b, o, l),
      _1883: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1884: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1885: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1886: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1887: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1888: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1889: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1890: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1891: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1892: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1893: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1894: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1895: Function.prototype.call.bind(DataView.prototype.getBigUint64),
      _1897: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1898: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1899: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1900: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1901: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1902: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1903: Function.prototype.call.bind(Number.prototype.toString),
      _1904: Function.prototype.call.bind(BigInt.prototype.toString),
      _1905: Function.prototype.call.bind(Number.prototype.toString),
      _1906: (d, digits) => d.toFixed(digits),
      _1912: (x0,x1) => x0.getContext(x1),
      _1917: () => globalThis.document,
      _1918: () => globalThis.window,
      _1923: (x0,x1) => { x0.height = x1 },
      _1925: (x0,x1) => { x0.width = x1 },
      _1927: (x0,x1) => { x0.pointerEvents = x1 },
      _1930: x0 => x0.head,
      _1931: x0 => x0.classList,
      _1935: (x0,x1) => { x0.innerText = x1 },
      _1936: x0 => x0.style,
      _1938: x0 => x0.sheet,
      _1939: x0 => x0.src,
      _1940: (x0,x1) => { x0.src = x1 },
      _1941: x0 => x0.naturalWidth,
      _1942: x0 => x0.naturalHeight,
      _1949: x0 => x0.offsetX,
      _1950: x0 => x0.offsetY,
      _1951: x0 => x0.button,
      _1958: x0 => x0.status,
      _1959: (x0,x1) => { x0.responseType = x1 },
      _1961: x0 => x0.response,
      _2010: (x0,x1) => { x0.responseType = x1 },
      _2011: x0 => x0.response,
      _2071: (x0,x1) => { x0.draggable = x1 },
      _2087: x0 => x0.style,
      _2444: (x0,x1) => { x0.target = x1 },
      _2446: (x0,x1) => { x0.download = x1 },
      _2471: (x0,x1) => { x0.href = x1 },
      _2564: (x0,x1) => { x0.src = x1 },
      _2659: x0 => x0.videoWidth,
      _2660: x0 => x0.videoHeight,
      _2672: (x0,x1) => { x0.kind = x1 },
      _2674: (x0,x1) => { x0.src = x1 },
      _2676: (x0,x1) => { x0.srclang = x1 },
      _2678: (x0,x1) => { x0.label = x1 },
      _2689: x0 => x0.error,
      _2691: (x0,x1) => { x0.src = x1 },
      _2692: x0 => x0.srcObject,
      _2693: (x0,x1) => { x0.srcObject = x1 },
      _2696: (x0,x1) => { x0.crossOrigin = x1 },
      _2699: (x0,x1) => { x0.preload = x1 },
      _2700: x0 => x0.buffered,
      _2703: x0 => x0.currentTime,
      _2704: (x0,x1) => { x0.currentTime = x1 },
      _2705: x0 => x0.duration,
      _2706: x0 => x0.paused,
      _2709: x0 => x0.playbackRate,
      _2710: (x0,x1) => { x0.playbackRate = x1 },
      _2717: (x0,x1) => { x0.autoplay = x1 },
      _2719: (x0,x1) => { x0.loop = x1 },
      _2721: (x0,x1) => { x0.controls = x1 },
      _2722: x0 => x0.volume,
      _2723: (x0,x1) => { x0.volume = x1 },
      _2724: x0 => x0.muted,
      _2725: (x0,x1) => { x0.muted = x1 },
      _2730: x0 => x0.textTracks,
      _2740: x0 => x0.code,
      _2741: x0 => x0.message,
      _2775: (x0,x1) => x0[x1],
      _2777: x0 => x0.length,
      _2792: (x0,x1) => { x0.mode = x1 },
      _2794: x0 => x0.activeCues,
      _2815: x0 => x0.length,
      _3011: (x0,x1) => { x0.accept = x1 },
      _3025: x0 => x0.files,
      _3051: (x0,x1) => { x0.multiple = x1 },
      _3069: (x0,x1) => { x0.type = x1 },
      _3317: x0 => x0.src,
      _3318: (x0,x1) => { x0.src = x1 },
      _3320: (x0,x1) => { x0.type = x1 },
      _3324: (x0,x1) => { x0.async = x1 },
      _3326: (x0,x1) => { x0.defer = x1 },
      _3338: (x0,x1) => { x0.charset = x1 },
      _3364: (x0,x1) => { x0.width = x1 },
      _3366: (x0,x1) => { x0.height = x1 },
      _3785: () => globalThis.window,
      _3822: x0 => x0.document,
      _3844: x0 => x0.navigator,
      _3848: x0 => x0.screen,
      _3851: x0 => x0.innerHeight,
      _3855: x0 => x0.screenLeft,
      _3859: x0 => x0.outerHeight,
      _3860: x0 => x0.devicePixelRatio,
      _4099: x0 => x0.isSecureContext,
      _4102: x0 => x0.crypto,
      _4107: x0 => x0.sessionStorage,
      _4108: x0 => x0.localStorage,
      _4167: x0 => x0.message,
      _4209: x0 => x0.clipboard,
      _4211: x0 => x0.geolocation,
      _4214: x0 => x0.mediaDevices,
      _4216: x0 => x0.permissions,
      _4217: x0 => x0.maxTouchPoints,
      _4224: x0 => x0.appCodeName,
      _4225: x0 => x0.appName,
      _4226: x0 => x0.appVersion,
      _4227: x0 => x0.platform,
      _4228: x0 => x0.product,
      _4229: x0 => x0.productSub,
      _4230: x0 => x0.userAgent,
      _4231: x0 => x0.vendor,
      _4232: x0 => x0.vendorSub,
      _4234: x0 => x0.language,
      _4235: x0 => x0.languages,
      _4236: x0 => x0.onLine,
      _4241: x0 => x0.hardwareConcurrency,
      _4281: x0 => x0.data,
      _4318: (x0,x1) => { x0.onmessage = x1 },
      _4438: x0 => x0.length,
      _4655: x0 => x0.readyState,
      _4664: x0 => x0.protocol,
      _4668: (x0,x1) => { x0.binaryType = x1 },
      _4671: x0 => x0.code,
      _4672: x0 => x0.reason,
      _5822: x0 => x0.destination,
      _5826: x0 => x0.state,
      _5827: x0 => x0.audioWorklet,
      _5929: (x0,x1) => { x0.fftSize = x1 },
      _5930: x0 => x0.frequencyBinCount,
      _5932: (x0,x1) => { x0.minDecibels = x1 },
      _5934: (x0,x1) => { x0.maxDecibels = x1 },
      _5936: (x0,x1) => { x0.smoothingTimeConstant = x1 },
      _6190: x0 => x0.port,
      _6329: x0 => x0.type,
      _6370: x0 => x0.signal,
      _6382: x0 => x0.length,
      _6426: x0 => x0.isConnected,
      _6431: x0 => x0.firstChild,
      _6442: () => globalThis.document,
      _6501: x0 => x0.documentElement,
      _6522: x0 => x0.body,
      _6524: x0 => x0.head,
      _6851: x0 => x0.id,
      _6852: (x0,x1) => { x0.id = x1 },
      _6876: (x0,x1) => { x0.innerHTML = x1 },
      _6879: x0 => x0.children,
      _8197: x0 => x0.value,
      _8199: x0 => x0.done,
      _8378: x0 => x0.size,
      _8379: x0 => x0.type,
      _8382: (x0,x1) => { x0.type = x1 },
      _8385: x0 => x0.name,
      _8391: x0 => x0.length,
      _8396: x0 => x0.result,
      _8765: x0 => x0.mimeType,
      _8766: x0 => x0.state,
      _8770: (x0,x1) => { x0.onstop = x1 },
      _8772: (x0,x1) => { x0.ondataavailable = x1 },
      _8785: (x0,x1) => { x0.audioBitsPerSecond = x1 },
      _8787: (x0,x1) => { x0.videoBitsPerSecond = x1 },
      _8797: x0 => x0.data,
      _8886: x0 => x0.url,
      _8888: x0 => x0.status,
      _8890: x0 => x0.statusText,
      _8891: x0 => x0.headers,
      _8892: x0 => x0.body,
      _8967: x0 => x0.types,
      _9154: x0 => x0.type,
      _9169: x0 => x0.matches,
      _9182: x0 => x0.width,
      _9183: x0 => x0.height,
      _9186: x0 => x0.orientation,
      _9273: x0 => x0.state,
      _9672: x0 => x0.active,
      _9704: x0 => x0.facingMode,
      _9918: x0 => x0.width,
      _9920: x0 => x0.height,
      _9930: x0 => x0.sampleRate,
      _9942: x0 => x0.channelCount,
      _10003: x0 => x0.deviceId,
      _10004: x0 => x0.kind,
      _10005: x0 => x0.label,
      _10580: x0 => x0.coords,
      _10581: x0 => x0.timestamp,
      _10583: x0 => x0.accuracy,
      _10584: x0 => x0.latitude,
      _10585: x0 => x0.longitude,
      _10586: x0 => x0.altitude,
      _10587: x0 => x0.altitudeAccuracy,
      _10588: x0 => x0.heading,
      _10589: x0 => x0.speed,
      _10590: x0 => x0.code,
      _10591: x0 => x0.message,
      _10999: (x0,x1) => { x0.border = x1 },
      _11277: (x0,x1) => { x0.display = x1 },
      _11441: (x0,x1) => { x0.height = x1 },
      _11635: (x0,x1) => { x0.objectFit = x1 },
      _11765: (x0,x1) => { x0.pointerEvents = x1 },
      _12063: (x0,x1) => { x0.transform = x1 },
      _12067: (x0,x1) => { x0.transformOrigin = x1 },
      _12131: (x0,x1) => { x0.width = x1 },
      _12422: x0 => x0.charging,
      _12425: x0 => x0.level,
      _12427: (x0,x1) => { x0.onchargingchange = x1 },
      _12499: x0 => x0.name,
      _12500: x0 => x0.message,
      _12503: x0 => x0.subtle,
      _13209: () => globalThis.console,
      _13233: x0 => x0.x,
      _13234: x0 => x0.y,
      _13235: x0 => x0.z,
      _13236: (x0,x1) => { x0.onreading = x1 },
      _13237: (x0,x1) => { x0.onerror = x1 },
      _13238: x0 => x0.x,
      _13239: x0 => x0.y,
      _13240: x0 => x0.z,
      _13241: (x0,x1) => { x0.onreading = x1 },
      _13242: (x0,x1) => { x0.onerror = x1 },
      _13243: x0 => x0.x,
      _13244: x0 => x0.y,
      _13245: x0 => x0.z,
      _13246: (x0,x1) => { x0.onreading = x1 },
      _13247: (x0,x1) => { x0.onerror = x1 },
      _13248: x0 => x0.x,
      _13249: x0 => x0.y,
      _13250: x0 => x0.z,
      _13251: (x0,x1) => { x0.onreading = x1 },
      _13252: (x0,x1) => { x0.onerror = x1 },
      _13253: x0 => x0.error,
      _13254: x0 => x0.name,
      _13255: x0 => x0.message,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      s: [
        "([ \r\n\t]+)|([!-\\[\\]-‧‪-퟿豈-￿][̀-ͯ]*|[\ud800-\udbff][\udc00-\udfff][̀-ͯ]*|\\\\verb\\*([^]).*?\\3|\\\\verb([^*a-zA-Z]).*?\\4|\\\\operatorname\\*|\\\\[a-zA-Z@]+[ \r\n\t]*|\\\\[^\ud800-\udfff])",
      ],
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
